//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class accdet
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "This field is mandatory")]
        [DataType(DataType.Text)]
        [RegularExpression("^[a-zA-Z']{1,50}", ErrorMessage = "Please enter valid Name")]
        [DisplayName("Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This field is mandatory")]

        public string Address { get; set; }
        [Required(ErrorMessage = "This field is mandatory")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^d{10}$", ErrorMessage = "Please enter valid phone number")]
        [DisplayName("Phone Number")]

        public string PhoneNumber { get; set; }
        [DisplayName("Alternate Phone Number")]
        [RegularExpression(@"^d{10}$", ErrorMessage = "Please enter valid phone number")]

        public string AlternatePhoneNumber { get; set; }

        [Required(ErrorMessage = "This field is mandatory")]
        [DataType(DataType.PostalCode)]
        [DisplayName("Pin Code")]
        [MaxLength(6),
        MinLength(6, ErrorMessage = "Please Enter a Valid Pin Code")]
        public string PinCode { get; set; }

        [Required(ErrorMessage = "This field is mandatory")]
        [DataType(DataType.Text)]
        [DisplayName("City")]

        public string City { get; set; }
    }
}
